#! /bin/sh

sxhkd &
$HOME/.fehbg
picom & 
$HOME/.config/polybar/launch.sh --colorblocks &
redshift &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor eDP-1 -d 1 2 3 4 5 
#bspc monitor HDMI-2 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
